---
name: Build ISOs (Live Anaconda)

on:
  schedule:
    - cron: "50 6 * * 0" # 06:50 UTC on Sundays
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Which image version to build'
        type: choice
        required: true
        default: 'latest'
        options:
          - gts
          - latest
          - all
      # upload_artifacts:
      #   description: 'Upload ISOs as job artifacts'
      #   type: boolean
      #   default: false
      # upload_r2:
      #   description: 'Upload ISOs to Cloudflare R2'
      #   type: boolean
      #   default: true
  pull_request:
    paths:
      - ".github/workflows/build-iso-anaconda.yml"
      - "build_files/iso/configure_iso_anaconda.sh"
  push:
    paths:
      - ".github/workflows/build-iso-anaconda.yml"
      - "build_files/iso/configure_iso_anaconda.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_NAME: "silver-ublue"

jobs:
  # Define which variants to build based on input
  determine-matrix:
    name: Determine Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set Matrix
        id: set-matrix
        run: |
          # Define the matrix based on the input selection
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            case "${{ github.event.inputs.image_version }}" in
              "gts")
                matrix='{"include":[
                  {"platform":"amd64","flavor":"main","image_version":"gts"}
                ]}'
                # {"platform":"amd64","flavor":"nvidia-open","image_version":"gts"}
                ;;
              "latest")
                matrix='{"include":[
                  {"platform":"amd64","flavor":"main","image_version":"latest"}
                ]}'
                # {"platform":"amd64","flavor":"nvidia-open","image_version":"latest"}
                ;;
              "all")
                matrix='{"include":[
                  {"platform":"amd64","flavor":"main","image_version":"gts"},
                  {"platform":"amd64","flavor":"main","image_version":"latest"}
                ]}'
                # {"platform":"amd64","flavor":"nvidia-open","image_version":"gts"},
                # {"platform":"amd64","flavor":"nvidia-open","image_version":"latest"}
                ;;
            esac
          else
            # Default for non-workflow_dispatch (like pull_request / push)
            matrix='{"include":[
              {"platform":"amd64","flavor":"main","image_version":"latest"}
            ]}'
            # {"platform":"amd64","flavor":"nvidia-open","image_version":"latest"}
          fi

          # Compact the JSON and output it
          compact_matrix=$(echo "$matrix" | jq -c .)
          echo "matrix=$compact_matrix" >>$GITHUB_OUTPUT
          echo "Generated matrix:"
          echo "$matrix" | jq .

  build:
    name: Build ISOs
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    needs: determine-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.determine-matrix.outputs.matrix) }}
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Install dependencies
        if: matrix.platform == 'arm64'
        run: |
          set -euxo pipefail
          sudo apt update -y
          sudo apt install -y podman

      - name: Maximize build space (remove-software)
        if: matrix. platform != 'arm64'
        uses: ublue-os/remove-unwanted-software@695eb75bc387dbcd9685a8e72d23439d8686cba6 # v10

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@695eb75bc387dbcd9685a8e72d23439d8686cba6 # v10

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        # with:
        #   submodules: recursive

      - name: Setup Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      # - name: Check Just Syntax
      #   shell: bash
      #   run: |
      #     set -euxo pipefail
      #     just check

      - name: Format image ref
        id: image_ref
        env:
          FLAVOR: ${{ matrix.flavor }}
        run: |
          set -euxo pipefail
          image_name=$(just image_name "silver-ublue" \
                "${{ matrix.image_version}}" "${{ matrix.flavor}}")
          image_ref="${IMAGE_REGISTRY}/${image_name}"
          KARGS="NONE"
          mkdir ${{ github.workspace }}/flatpaks
          sed 's/ *#.*//; /^$/d' \
                "${{ github.workspace }}/build_files/iso/system-flatpaks.list" \
                >${{ github.workspace }}/flatpaks/system-flatpaks.list
          echo "image_ref=$image_ref" >>"${GITHUB_OUTPUT}"
          echo "artifact_format=$image_name-${{ matrix.image_version }}-$(uname -m)" \
                >>"${GITHUB_OUTPUT}"
          echo "kargs=$KARGS" >>"${GITHUB_OUTPUT}"

      - name: Build ISO
        id: build
        uses: ublue-os/titanoboa@main
        with:
          image-ref: ${{ steps.image_ref.outputs.image_ref }}:${{ matrix.image_version }}
          flatpaks-list: ${{ github.workspace }}/flatpaks/system-flatpaks.list
          kargs: ${{ steps.image_ref.outputs.kargs }}

      - name: Rename ISO
        id: rename
        env:
          OUTPUT_PATH: ${{ steps.build.outputs.iso-dest }}
          FLAVOR: ${{ matrix.flavor }}
          OUTPUT_NAME: ${{ steps.image_ref.outputs.artifact_format }}
          IMAGE_VERSION: ${{ matrix.image_version }}
        run: |
          set -euxo pipefail
          mkdir -p output
          OUTPUT_DIRECTORY="$(realpath output)"
          sha256sum "${OUTPUT_PATH}" |
                tee "${OUTPUT_DIRECTORY}/${OUTPUT_NAME}.iso-CHECKSUM"
          mv "${OUTPUT_PATH}" "${OUTPUT_DIRECTORY}/${OUTPUT_NAME}.iso"
          echo "output_directory=$OUTPUT_DIRECTORY" >>"${GITHUB_OUTPUT}"

      - name: Upload to Job Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: ${{ steps.image_ref.outputs.artifact_format }}
          if-no-files-found: error
          path: ${{ steps.rename.outputs.output_directory }}

      - name: Upload ISOs and Checksum to R2 Bucket
        if: github.ref_name == 'main'
        shell: bash
        env:
          RCLONE_CONFIG_S3_TYPE: s3
          RCLONE_CONFIG_S3_PROVIDER: ${{ secrets.S3_PROVIDER }}
          RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_S3_REGION: ${{ secrets.S3_REGION }}
          RCLONE_CONFIG_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          SOURCE_DIR: ${{ steps.rename.outputs.output_directory }}
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y rclone
          rclone copy --log-level INFO --checksum "${SOURCE_DIR}" \
                S3:${{ secrets.S3_BUCKET_NAME }}